---
name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Java
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'
      - name: setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 2.9.1
      - name: test
        run: lein test
